### ISSUE TITLE
Add Skip Link to Main Content

### ISSUE THREAD

**Issue by codyogden** [approachable-io/approachable-io#15]
We should provide a ['skip link'](https://webaim.org/techniques/skipnav/) at the top of the page which allows the user to a target the main content on the page. This ensures our content is accessible for any users with visual or motor disabilities. The skip link can be added by altering the HTML to include the skip link and its target. For example:

```html
...
<body>
    <a href="#main-content" class="skip-link">Skip to Main Content</a> 
    ...
    <div class="text-container" id="main-content">
        ...
    </div>
    ...
```

CSS can visually hide the skip link and while ensuring it is accessible to users via keyboard navigation. [WebAIM](https://webaim.org/techniques/css/invisiblecontent/) suggests something like this:

```css
a.skip-link {
  position: absolute;
  top: -99999px;
  left: -99999px;
}

a.skip-link:focus {
  top: 0;
  left: 0;
}
```
