### ISSUE TITLE
Add width and max-width to img tags

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/approachable-io#7]
Limit the size of the logo by changing the `img` tag in the `styles.css` to something like this:

```css
img {
  width: 100%;
  max-width: 400px;
}
```

This should also go hand in hand with centering the image, but that can be moved to a separate issue if you don't feel comfortable making that change.
